name: Cleanup old branches
on:
  push:
    branches:
      - main
      - develop
  schedule:
      - cron: "*/10 * * * *"
jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@v0.0.6
        with:
          repo_token: ${{ github.token }}
          date: '3 months ago'
          dry_run: true
          delete_tags: false
          extra_protected_branch_regex: ^(main|rapid-*|standard-*)$
